%YAML 1.2
---

http:
  port: "8081"
  
database:
  uhub:
    name: "![gxAsmVI6bIudM0Mx9yKo8Q==]"
    host: "serverless-europe-west3.sysp0000.db2.skysql.com"
    port: "4071"
    user: "![NTd9zpaYLoQdsG8jGWsdIQ==]"
    password: "![+shCywT9+4g1jCRc4fGbamvfQm9erS9hIturLDQTM8Y=]"
  
  
  
  